### PR TITLE
Create CNAME for moeditor.js.org

### PR DESCRIPTION
**Pull request by SevenOutman**
CNAME to `moeditor.js.org`. As soon as this PR is merged, I will [apply for that domain again](https://github.com/js-org/dns.js.org/pull/1927).

### CODE REVIEW

**Comment by Menci** [comment]
Sure but how it works?

**Comment by SevenOutman** [comment]
@Menci [`js-org/dns.js.org`](https://github.com/js-org/dns.js.org) is a service helping js developers to have their own dedicated domain names. If your site matches its rules, you can apply for a `*.js.org` sub domain name by opening a PR.

**Comment by Menci** [comment]
https://moeditor.js.org/ very slow in China. Can we use my own server with its domain?

**Comment by SevenOutman** [comment]
@Menci Technically yes you can. All you need to do is cname your own domain to `moeditor.js.org`, then apply for it with a PR to `js-org/dns.js.org`. But I want to take advantage of Project GitHub Pages, that is, when `moeditor.js.org` points to `moeditor.github.io`, `moeditor.js.org/online` also points to `moeditor.github.io/online`, which is `Moeditor/online` repo's GitHub Pages. As for the slow speed you mentioned, accessibility to GitHub Pages is theoretically the same as to GitHub. So if visitors to `moeditor.js.org` are mostly GitHub users, I'd recommend use GitHub Pages instead of an external server.

**Pull request merged**
